### ISSUE TITLE
Message not sent

### ISSUE THREAD

**Issue by ackid32** [MohammadFneish7/WhatsappAgent#15]
Sorry to disturb you, This is a great work. Now I have one problem that is - till yesterday, the message was sent perfectly. But now all messages are in draft. Not working. Please verify. Thanks in advance.

**Comment by alhuntre** [comment]
Hello ackid32,

Firstly, I would like to thank the developer for this amazing library. I've been using the library for a few months now, and I encountered the same problem at the same period that you did. I think the issue lies within the method (WaitForCSSElemnt("[title='Type a message']", load_timeout).SendKeys(Keys.Enter)). It tries to find the title 'type message' and cannot, resulting in failure or a timeout, and the message is saved in drafts.

For a quick fix, I managed to change this line to 

`(Wait(15u);

Actions actions = new(driver);
actions.KeyDown(Keys.Enter);
actions.Perform();)`.

Remember, this is a temporary fix and may not be optimal, but it should work for some time.

Thank you again, Mohammad Fneish, for the great library.

**Comment by ackid32** [comment]
Hi mawadidres,
Yes,the issue lies within the method (WaitForCSSElemnt("[title='Type a message']", load_timeout).SendKeys(Keys.Enter)). 

I found that the title element is not there and instead of that 'aria-label' is there. So I change it to 
var textbox = WaitForCSSElemnt("[aria-label='Type a message']", load_timeout);

it works fine.

**Comment by alhuntre** [comment]
Hello again,

I just found the solution and came here to update my comment. Thank you very much. I hope WhatsApp doesn't change anything else for a long time! Lol!

**Comment by ackid32** [comment]
> Hello again,
> 
> I just found the solution and came here to update my comment. Thank you very much. I hope WhatsApp doesn't change anything else for a long time! Lol!

Hi, I have issues with sending images. Do you?

**Comment by MohammadFneish7** [comment]
Hello @ackid32 @mawadidres, thanks for your feedback and sorry for being late on reply, I was so busy with other things. Whatsapp has made some changes to its html document structure and that was causing an issue in both text and media simulation. I've made necessary changes to fix those issues. Please pull new my changes to have the updates. Have a nice day!

**Comment by ackid32** [comment]
> Hello @ackid32 @mawadidres, thanks for your feedback and sorry for being late on reply, I was so busy with other things. Whatsapp has made some changes to its html document structure and that was causing an issue in both text and media simulation. I've made necessary changes to fix those issues. Please pull new my changes to have the updates. Have a nice day!

Thanks for the fix. But this fixes the text message but not sendmedia. Please check. And one more question that where the session files are stored (I want to delete that to test again)
